"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
# Em config/settings.py
import os
from dotenv import load_dotenv # Importa o leitor de .env

# Carrega as variáveis do arquivo .env para o ambiente
load_dotenv()

# ... (o resto do arquivo settings.py continua abaixo)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%c_ssl$x70nz)ekj$$6@jr()q03w!i4^*fcs_a53hgd*(()#o*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_countries',
    'social_django',
    'analytics',
    'accounts',
    'core',
    'subscriptions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '1030026652721-39u6uokp85lkjvuuoi0f3clm9hgmq2l1.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'


SOCIAL_AUTH_GOOGLE_OAUTH2_EXTRA_DATA = ['first_name', 'last_name', 'picture']

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'error',
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Em config/settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Em config/settings.py

STATIC_URL = '/static/'

# ADICIONE ISTO AQUI:
# Diz ao Django: "Procure arquivos também na pasta 'static' na raiz do projeto"
import os
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Em config/settings.py

# Para onde o @login_required deve redirecionar (USE O NOME DA ROTA DE LOGIN)
LOGIN_URL = 'login' # <-- Mude 'login' para o NOME da sua rota de login

# Para onde o usuário vai DEPOIS que o login dá certo
LOGIN_REDIRECT_URL = 'dashboard_home' # (Esse já está certo)

# Para onde o usuário vai DEPOIS do logout
LOGOUT_REDIRECT_URL = 'home' # (Opcional, mas bom)

# Diz ao Django para usar nosso usuário customizado em vez do padrão
AUTH_USER_MODEL = 'accounts.CustomUser'

# Em config/settings.py

# ... (outras configurações) ...

# --- Configurações do Social Auth (Google) ---

# Define as "permissões" que vamos pedir ao usuário
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',      # Pega o email
    'https://www.googleapis.com/auth/userinfo.profile',    # Pega nome/foto
    'https://www.googleapis.com/auth/youtube.readonly',    # Vê dados públicos (vídeos, etc)
    'https://www.googleapis.com/auth/yt-analytics.readonly', # Vê dados PRIVADOS (impressões, etc)
    'https://www.googleapis.com/auth/youtube.force-ssl', # Acesso mais forte (só pra garantir)
]

# Pede um "refresh token". Isso é VITAL.
# Permite que nosso app pegue os dados do YouTube mesmo
# quando o usuário não está ativamente logado.
# Em config/settings.py

# ... (outras configurações) ...

# JÁ TEMOS ISSO (garante que estamos pedindo o refresh_token):
SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
    'access_type': 'offline',
    'prompt': 'consent'
}

# --- A LINHA QUE FALTAVA ---
# Diz ao pipeline para EXPLICITAMENTE salvar o refresh_token
# no campo 'extra_data' do UserSocialAuth.
SOCIAL_AUTH_GOOGLE_OAUTH2_EXTRA_DATA = [
    'refresh_token',
    'expires_in',
    'token_type',
]

# (Opcional, mas não custa)
# Garante que o pipeline de associação por email esteja ativo
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email', # <-- Garante que está aqui
    'social_core.pipeline.user.create_user',
    'accounts.pipeline.save_youtube_channel_data',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)
# Em config/settings.py

# ... (outras configurações) ...

# --- Configuração de Cookies para Login OAuth ---
# Garante que os cookies de sessão e CSRF sejam enviados
# de volta após o redirecionamento do Google.

SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Em config/settings.py

# ... (outras configs) ...

# --- Configuração de Cache do Banco de Dados ---
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'youtube_data_cache', # Nome da tabela que será criada
    }
}

# Em config/settings.py (No final)

# Configurações de Arquivos de Mídia (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Em config/settings.py

# Configurações de Envio de Email Real (Gmail)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

